<?php

/**
 * @file
 * hook_contact module.
 */

/*
	this function to add many variable for this specific template
*/

function hook_contact_preprocess_node__page_contact(&$variables){

	// get current node ID
	$node = \Drupal::routeMatch()->getParameter('node');

	// get all data for the page
	$data = getContentContact($node->id());

	//set variables, get them from twig template
	$variables['data'] = $data;

}

function getContentContact($nid){

	$data = [];
	/*
	* Get picture on top for fold1
	*/
	$query = db_query("
		SELECT f.uri, p.field_poster_alt,
		p.field_poster_title
		from file_managed f
		join node__field_poster p
		on f.fid = p.field_poster_target_id
		where p.entity_id = $nid
	");

	$pictureOnTop = $query->fetchAll();

	// Convert style image
	$pictureOnTop[0]->uri = entity_load('image_style', '2000_par_600')->buildUrl($pictureOnTop[0]->uri);

	// add to global var data
	$data['pictureOnTop'] = $pictureOnTop[0];

	//Get intro
	$query = db_query("
		SELECT i.field_intro_contact_value
		FROM node__field_intro_contact i
	");

	$intro = $query->fetchAll();
	$data['intro'] = $intro[0]->field_intro_contact_value;

	//Get address
	$query = db_query("
		SELECT i.field_infos_gris_value
		FROM node__field_infos_gris i
	");

	$address = $query->fetchAll();
	$data['address'] = $address[0]->field_infos_gris_value;


	/*
	* Get Event datas
	*/
	/*$query = db_query("
		SELECT l.field_place_value as lieu,
		e.field_moment_evt_value as date,
		b.body_value as description
		FROM aveyron.node_field_data d
		join node__field_poster p
		on p.entity_id = d.nid
		join node__field_place l
		on l.entity_id = d.nid
		join node__field_moment_evt e
		on e.entity_id = d.nid
		join node__body b
		on b.entity_id = d.nid
		where d.nid = $nid
	");

	$events = $query->fetchAll();
	$data['events'] = $events[0];


	$query = db_query("
		SELECT d.title, d.nid, m.uri
		FROM aveyron.node_field_data d
		join node__field_poster p
		on p.entity_id = d.nid
		join file_managed m
		on m.fid = p.field_poster_target_id
		where d.type = 'event'
		and d.nid not like $nid
		order by rand() limit 2
	");

	$events = $query->fetchAll();

	foreach ($events as $key => $event) {

		//Add alias path
		$path_alias = \Drupal::service('path.alias_manager')->getAliasByPath("/node/".$event->nid);
		$path_alias = ltrim($path_alias, '/');
		$event->url_alias = $path_alias;

		// convert style
		$event->uri = entity_load('image_style', '200_par_200')->buildUrl($event->uri);

		// remove useless properties
		unset($event->nid);

	}

	$data['events']->prev = $events[0];
	$data['events']->next = $events[1];*/




	return $data;

}