<?php
function layer_leaflet_leaflet_map_info() {
  $default_settings = array(
    'attributionControl' => TRUE,
    'closePopupOnClick'  => TRUE,
    'doubleClickZoom'    => TRUE,
    'dragging'           => TRUE,
    'fadeAnimation'      => TRUE,
    'layerControl'       => FALSE,
    'maxZoom'            => 18,
    'minZoom'            => 14,
    'scrollWheelZoom'    => TRUE,
    'touchZoom'          => TRUE,
    'trackResize'        => TRUE,
    // Don't specify, if you want to use Auto-box.
    // 'zoom'               =>  2,
    'zoomAnimation'      => TRUE,
    'zoomControl'        => TRUE,
  );
  $map_info = array();
  $map_info['IGN GRIDSYSTEM'] = array(
    'label' => 'IGN GRIDSYSTEM',
    'description' => 'IGN GRIDSYSTEM',
    'settings' => $default_settings,
    'layers' => array(
      'layer' => array(
        'urlTemplate' => '//wxs.ign.fr/keivyuqi9olxo91z3g5xvh5z/geoportail/wmts?service=WMTS&request=GetTile&version=1.0.0&tilematrixset=PM&tilematrix={z}&tilecol={x}&tilerow={y}&layer=GEOGRAPHICALGRIDSYSTEMS.MAPS&format=image/jpeg&style=normal',
        'options' => array(
          'attribution' => 'Carte IGN',
          'detectRetina' => TRUE,
        ),
      ),
    ),
  );
  return $map_info;
}
