<?php

/**
 * @file
 * hook_ens module.
 */

/*
	this function to add many variable for this specific template
*/
function hook_hp_preprocess_node__ens(&$variables){

	// get current node ID
	$node = \Drupal::routeMatch()->getParameter('node');

	// get all data for the page
	$data = getContent($node->id());

	//set variables, get them from twig template
	$variables['data'] = $data;

}

function getContent($nid){

	$data = [];

	/*
	* Get picture on top for fold1
	*/
	$query = db_query("
		SELECT f.uri, p.field_poster_alt,
		p.field_poster_title
		from file_managed f
		join node__field_poster p
		on f.fid = p.field_poster_target_id
		where p.entity_id = $nid
	");

	$pictureOnTop = $query->fetchAll();

	// Convert style image
	$pictureOnTop[0]->uri = entity_load('image_style', '2000_par_600')->buildUrl($pictureOnTop[0]->uri);
	//$pictureOnTop[0]->uri = file_create_url($pictureOnTop[0]->uri);

	// add to global var data
	$data['pictureOnTop'] = $pictureOnTop[0];

	/*
	* Get description
	*/
	$query = db_query("
		SELECT b.body_value FROM node__body b where b.entity_id = ".$nid."
	");

	$descro = $query->fetchAll();

	// add to global var data
	$data['description'] = $descro[0];

	/*
	* Get videos
	*/
	$query = db_query("
		SELECT v.field_video_ens_value FROM node__field_video_ens v where v.entity_id = $nid
	");

	$videos = $query->fetchAll();

	// add to global var data
	$data['videos'] = $videos;



	/*
	* Get pictures's gallerie
	*/
	$query = db_query("
		SELECT f.uri, g.field_gallery_alt,
		g.field_gallery_title
		from file_managed f
		join node__field_gallery g
		on f.fid = g.field_gallery_target_id
		where g.entity_id = $nid
	");

	$pictures = $query->fetchAll();

	foreach ($pictures as $key => $picture) {

		$picture->uri = entity_load('image_style', '500_par_350')->buildUrl($picture->uri);

	}

	// add to global var data
	$data['videos'] = $pictures;


	/*
	* Get lat/lon value of ens
	*/
	$query = db_query("
		SELECT t.field_start_trace_lat, t.field_start_trace_lon
		FROM node__field_start_trace t
		where t.entity_id = $nid
	");

	$latLon = $query->fetchAll();

	// add to global var data
	$data['depart'] = $latLon[0];

	/*
	* Get wkt trace value of ens
	*/
	$query = db_query("
		SELECT t.field_trace_value
		FROM node__field_trace t
		where t.entity_id = $nid
	");

	$trace = $query->fetchAll();

	// add to global var data
	$data['trace'] = $trace;


	/*
	* Get ens of similar thematique
	*/
	// 1st : get thematique id
	$query = db_query("
		SELECT t.field_thematique_ens_target_id
		FROM node__field_thematique_ens t
		where t.entity_id = $nid
	");

	$thematique = $query->fetchAll();

	$thematiqueID = $thematique[0]->field_thematique_ens_target_id;

	$query = db_query("
		SELECT d.title, d.nid, u.field_start_trace_lat, u.field_start_trace_lon, m.uri
		FROM node_field_data d
		join node__field_thematique_ens t
		on t.entity_id = d.nid
		join node__field_start_trace u
		on u.entity_id = d.nid
		join node__field_poster p
		on p.entity_id = d.nid
		join file_managed m
		on m.fid = p.field_poster_target_id
		where t.field_thematique_ens_target_id = $thematiqueID
		and d.nid <> $nid ORDER BY RAND() LIMIT 3
	");

	// 2nd : get ens title + poster + lat/lon
	$similarsENS = $query->fetchAll();

	foreach ($similarsENS as $key => $similarENS) {

		$similarENS->uri = entity_load('image_style', '500_par_350')->buildUrl($similarENS->uri);

	}

	// add to global var data
	$data['similarsENS'] = $similarsENS;


	/*
	* Get taxons
	*/

	return $data;

}