<?php

/**
 * @file
 * hook_hp module.
 */

/*
	this function to add many variable for this specific template
*/
function hook_hp_preprocess_node__ens(&$variables){

	$node = \Drupal::routeMatch()->getParameter('node');

	$picturesFold1 = getPicturesFold1($node->id());
	$variables['picturesFold1'] = $node->id();

	//set variables

}

function getPicturesFold1($nid){

	$query = db_query("
		SELECT f.uri, s.field_image_on_top_alt,
		s.field_image_on_top_title
		from file_managed f
		join node__field_image_on_top s
		on f.fid = s.field_image_on_top_target_id
	");

	$pictureOnTop = $query->fetchAll();

	//$ens->uri = entity_load('image_style', '470_par_750')->buildUrl($ens->uri);
	$pictureOnTop[0]->uri = file_create_url($pictureOnTop[0]->uri);
	return $pictureOnTop[0];

}