<?php

/**
 * @file
 * hook_taxon module.
 */

/*
	this function to add many variable for this specific template
*/

function hook_event_preprocess_node__taxon(&$variables){

	// get current node ID
	$node = \Drupal::routeMatch()->getParameter('node');

	// get all data for the page
	$data = getContentTaxon($node->id());

	//set variables, get them from twig template
	$variables['data'] = $data;

}

function getContentTaxon($nid){

	$data = [];

	/*
	* Get Taxons datas
	*/
	$query = db_query("
		SELECT b.body_value as description
		FROM aveyron.node_field_data d
		join node__body b
		on b.entity_id = d.nid
		where d.nid = $nid
	");

	$taxons = $query->fetchAll();
	$data['taxons'] = $taxons[0];


	$query = db_query("
		SELECT d.title, d.nid, m.uri
		FROM aveyron.node_field_data d
		join node__field_poster p
		on p.entity_id = d.nid
		join file_managed m
		on m.fid = p.field_poster_target_id
		where d.type = 'taxon'
		and d.nid not like $nid
		order by rand() limit 2
	");

	$taxons = $query->fetchAll();

	foreach ($taxons as $key => $event) {

		//Add alias path
		$path_alias = \Drupal::service('path.alias_manager')->getAliasByPath("/node/".$event->nid);
		$path_alias = ltrim($path_alias, '/');
		$event->url_alias = $path_alias;

		// convert style
		$event->uri = entity_load('image_style', '200_par_200')->buildUrl($event->uri);

		// remove useless properties
		unset($event->nid);

	}

	$data['taxons']->prev = $taxons[0];
	$data['taxons']->next = $taxons[1];




	return $data;

}