<?php

/**
 * @file
 * hook_event module.
 */

/*
	this function to add many variable for this specific template
*/

function hook_event_preprocess_node__event(&$variables){

	// get current node ID
	$node = \Drupal::routeMatch()->getParameter('node');

	// get all data for the page
	$data = getContentEvent($node->id());

	//set variables, get them from twig template
	$variables['data'] = $data;

}

function getContentEvent($nid){

	$data = [];

	/*
	* Get Event datas
	*/
	$query = db_query("
		SELECT l.field_place_value as lieu,
		e.field_moment_evt_value as date,
		b.body_value as description
		FROM aveyron.node_field_data d
		join node__field_poster p
		on p.entity_id = d.nid
		join node__field_place l
		on l.entity_id = d.nid
		join node__field_moment_evt e
		on e.entity_id = d.nid
		join node__body b
		on b.entity_id = d.nid
		where d.nid = $nid
	");

	$events = $query->fetchAll();
	$data['events'] = $events[0];


	$query = db_query("
		SELECT d.title, d.nid, m.uri
		FROM aveyron.node_field_data d
		join node__field_poster p
		on p.entity_id = d.nid
		join file_managed m
		on m.fid = p.field_poster_target_id
		where d.type = 'event'
		and d.nid not like $nid
		order by rand() limit 2
	");

	$events = $query->fetchAll();

	foreach ($events as $key => $event) {

		//Add alias path
		$path_alias = \Drupal::service('path.alias_manager')->getAliasByPath("/node/".$event->nid);
		$path_alias = ltrim($path_alias, '/');
		$event->url_alias = $path_alias;

		// convert style
		$event->uri = entity_load('image_style', '200_par_200')->buildUrl($event->uri);

		// remove useless properties
		unset($event->nid);

	}

	$data['events']->prev = $events[0];
	$data['events']->next = $events[1];




	return $data;

}